# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- KubeManifestsDeploy

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
    - job: PublishBuildArtifacts
      steps:
      - task: PublishPipelineArtifact@1
        displayName: Publish Artifacts
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/kube-manifests'
          artifact: 'kube-manifests-out'
          publishLocation: 'pipeline'

# - stage: Deploy
#   displayName: Deploy stage
#   #dependsOn: Build
#   jobs:
#   - deployment: Deploy
#     displayName: Deploy
#     pool:
#       vmImage: $(vmImageName)
#     environment: 'rishabhbeniazuredevopsakskubernetesterraformpipeline.default'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: KubernetesManifest@0
#             displayName: Deploy to Kubernetes cluster
#             inputs:
#               action: 'deploy'
#               kubernetesServiceConnection: 'terraform-aks-dev-cluster-default'
#               namespace: 'default'
#               manifests: $(System.ArtifactsDirectory)/kube-manifests-out/01-Webserver-Apps